---
- name: Converge
  hosts: all
  become: true
  vars:
    service_name: molecule-command
    service_description: Molecule command service
    service_exec_start: /bin/sleep infinity
    service_restart: on-failure
    deploy_service_no_log: false
  tasks:
    - name: Include role under test
      ansible.builtin.include_role:
        name: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
